name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: ChenQiqian
        reponame: campus-net
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
        cname: blog.cqqqwq.com
        gitname: github-actions[bot]
        gitemail: github-actions[bot]@users.noreply.github.com